name: main

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build and deploy
    uses: ./.github/workflows/build_deploy.yaml
    with:
      environment: production
      image: app-monitoramento-realtime-maxtrack
      namespace: monitoramento-realtime-maxtrack
      ingress_name: app-monitoramento-realtime-maxtrack-ingress
      ingress_url: monitoramento-maxtrack.mobilidade.rio
      service: app-monitoramento-realtime-maxtrack-svc
      pod_name: app-monitoramento-realtime-maxtrack
      secret_name: app-monitoramento-realtime-maxtrack-ingress
      replicas: 6
    secrets: inherit
